name: surprise-benchmark
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy=1.26.0
  - pandas=2.1.1
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - attrs=23.1.0
  - tqdm=4.66.1
  - pyarrow=13.0.0
  - requests=2.31.0
  - openai=0.28.1
  - cattrs=23.1.2
  - tiktoken=0.5.1